# Generated by Django 4.2 on 2023-04-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_role_permissions_delete_permission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Customer"), (1, "Supervisor")], default=0
            ),
        ),
    ]
