# Generated by Django 4.2 on 2023-04-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[("Customer", "Customer"), ("Supervisor", "Supervisor")],
                default="Customer",
                max_length=50,
            ),
        ),
    ]
